import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactNode } from "react";

import { AppProvides } from "@/providers/AppProvides";

const myLocalFont = localFont({
  src: "./../fonts/Web437_IBM_VGA_9x16.woff",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={myLocalFont.className}>
      <body>
        <AppProvides>{children}</AppProvides>
      </body>
    </html>
  );
}
